### ISSUE TITLE
SO 

### ISSUE THREAD

**Issue by xyzza** [simonvorobjev/python#1]
Добрый день, Семен, не знаю как с вами связаться, потому пишу сюда.
Подскажите, где можно найти используемые вами файлы вот тут:
https://github.com/simonvorobjev/CryptoApi/blob/master/crypto_support.py#L11
и тут
https://github.com/simonvorobjev/CryptoApi/blob/master/crypto_support.py#L12

В стандартной поставке КриптоПро не нашел (возможно плохо искал).
Я так понимаю, что это скомпилированные расширения под Python

**Comment by simonvorobjev** [comment]
> Добрый день, Семен, не знаю как с вами связаться, потому пишу сюда.
> Подскажите, где можно найти используемые вами файлы вот тут:
> https://github.com/simonvorobjev/CryptoApi/blob/master/crypto_support.py#L11
> и тут
> https://github.com/simonvorobjev/CryptoApi/blob/master/crypto_support.py#L12
> 
> В стандартной поставке КриптоПро не нашел (возможно плохо искал).
> Я так понимаю, что это скомпилированные расширения под Python

Эти библиотеки входят в КриптоПро в пакет capilite.
